"""Interactive demo mode — showcases all CodeAgent features for client presentations."""

from __future__ import annotations
import time
import os

from rich.text import Text
from rich.panel import Panel
from rich.markdown import Markdown
from rich.columns import Columns

from .ui.console import console
from .ui import print_tool_call, print_tool_result, print_assistant, Spinner
from .tools import registry


# Each demo step: (user_prompt, tool_name, tool_args, ai_response)
DEMO_STEPS = [
    {
        "user": "Read the pyproject.toml file",
        "tool": "file_read",
        "args": {"path": "pyproject.toml"},
        "response": (
            "Here's your `pyproject.toml`. The project is set up with:\n\n"
            "- **Python 3.10+** required\n"
            "- **6 dependencies**: anthropic, openai, rich, click, python-dotenv, prompt-toolkit\n"
            "- **Entry point**: `codeagent` CLI command\n\n"
            "Everything looks well-configured for a modern Python package."
        ),
    },
    {
        "user": "List all files in the project",
        "tool": "directory_list",
        "args": {"path": ".", "recursive": True},
        "response": (
            "The project has a clean modular structure:\n\n"
            "- `codeagent/llm/` — LLM providers (Claude, OpenAI, Ollama)\n"
            "- `codeagent/tools/` — 7 agent tools (file ops, search, git, terminal)\n"
            "- `codeagent/ui/` — Rich terminal UI components\n\n"
            "Well-organized codebase following Python best practices."
        ),
    },
    {
        "user": "Search for all 'def execute' in the tools folder",
        "tool": "code_search",
        "args": {"pattern": "def execute", "path": "codeagent/tools", "glob": "*.py"},
        "response": (
            "Found **7 tool implementations**, each with its own `execute` method:\n\n"
            "1. **file_read** — Read files with line numbers\n"
            "2. **file_write** — Create/overwrite files\n"
            "3. **file_edit** — Surgical string replacement\n"
            "4. **directory_list** — Browse project structure\n"
            "5. **code_search** — Regex search across codebase\n"
            "6. **terminal** — Execute shell commands safely\n"
            "7. **git_ops** — Git status, diff, commit, log\n\n"
            "All tools follow the same `BaseTool` interface — easy to extend with new tools."
        ),
    },
    {
        "user": "Show me the git status",
        "tool": "git_ops",
        "args": {"operation": "status"},
        "response": (
            "Git is tracking the project. You can ask me to:\n\n"
            "- `git diff` to see changes\n"
            "- `git add` and `commit` your work\n"
            "- `git log` to review history\n\n"
            "I'll handle all git operations through the agent tools."
        ),
    },
    {
        "user": "Create a hello_world.py file",
        "tool": "file_write",
        "args": {
            "path": "hello_world.py",
            "content": (
                '#!/usr/bin/env python3\n'
                '"""Hello World — generated by CodeAgent."""\n'
                '\n'
                '\n'
                'def greet(name: str = "World") -> str:\n'
                '    """Return a greeting message."""\n'
                '    return f"Hello, {name}! Welcome to CodeAgent."\n'
                '\n'
                '\n'
                'if __name__ == "__main__":\n'
                '    print(greet())\n'
                '    print(greet("Client"))\n'
            ),
        },
        "response": (
            "Created `hello_world.py` with:\n\n"
            "- A typed `greet()` function with default parameter\n"
            "- Docstring and proper module structure\n"
            "- Main block for direct execution\n\n"
            "Let me run it to verify it works..."
        ),
    },
    {
        "user": "Run the hello_world.py file",
        "tool": "terminal",
        "args": {"command": "python3 hello_world.py"},
        "response": (
            "The file runs perfectly! CodeAgent can:\n\n"
            "- **Write** production-quality code\n"
            "- **Execute** it immediately to verify\n"
            "- **Debug** if something goes wrong\n"
            "- **Edit** existing files with precision\n\n"
            "All within the same conversation. No context switching needed."
        ),
    },
    {
        "user": "Edit hello_world.py — change 'World' to 'CodeAgent'",
        "tool": "file_edit",
        "args": {
            "path": "hello_world.py",
            "old_string": '"World"',
            "new_string": '"CodeAgent"',
        },
        "response": (
            "Edited the file with a precise string replacement. "
            "The default greeting now says **\"Hello, CodeAgent!\"**\n\n"
            "This is how the agent edits code — exact string matching, "
            "no accidental changes to other parts of the file."
        ),
    },
]


def _type_text(text: str, delay: float = 0.03) -> None:
    """Simulate typing effect."""
    for char in text:
        console.file.write(char)
        console.file.flush()
        time.sleep(delay)
    console.file.write("\n")
    console.file.flush()


def _pause(seconds: float = 1.0) -> None:
    time.sleep(seconds)


def run_demo() -> None:
    """Run the polished client demo."""
    # Welcome banner
    console.print()
    welcome = Text()
    welcome.append("CodeAgent", style="bold cyan")
    welcome.append(" — AI Coding Assistant\n", style="dim")
    welcome.append("Model: Claude Sonnet 4 (Anthropic)\n", style="info")
    welcome.append("Type ", style="dim")
    welcome.append("/help", style="bold")
    welcome.append(" for commands, ", style="dim")
    welcome.append("/quit", style="bold")
    welcome.append(" to exit", style="dim")
    console.print(Panel(welcome, border_style="cyan", padding=(0, 1)))
    _pause(1.5)

    for i, step in enumerate(DEMO_STEPS):
        # Show user input
        console.print()
        console.print(Text.assemble(
            ("> ", "bold green"),
            (step["user"], "bold white"),
        ))
        _pause(1.0)

        # Show thinking spinner
        with Spinner("Thinking..."):
            _pause(1.5)

        # Show tool call
        print_tool_call(step["tool"], step["args"])
        _pause(0.5)

        # Execute the REAL tool
        result = registry.execute(step["tool"], step["args"])
        print_tool_result(step["tool"], result)
        _pause(1.0)

        # Show AI response
        print_assistant(step["response"])
        _pause(2.0)

    # Closing
    console.print()
    console.print(Panel(
        Text.assemble(
            ("Demo Complete!", "bold green"),
            ("\n\n", ""),
            ("CodeAgent Features:\n", "bold cyan"),
            ("  7 built-in tools", ""), (" — file ops, search, git, terminal\n", "dim"),
            ("  Multi-provider", ""), (" — Claude, OpenAI, Ollama (local)\n", "dim"),
            ("  Streaming responses", ""), (" — real-time output\n", "dim"),
            ("  Tool chaining", ""), (" — agent uses multiple tools per task\n", "dim"),
            ("  Beautiful UI", ""), (" — panels, syntax highlighting, spinners\n", "dim"),
            ("  Safe by design", ""), (" — confirms destructive operations\n", "dim"),
        ),
        border_style="green",
        padding=(1, 2),
    ))

    # Cleanup demo file
    try:
        os.remove("hello_world.py")
    except FileNotFoundError:
        pass
